// Transactional email via Resend (https://resend.com), logged to shop_email_events.
// A dedupe key makes every send idempotent: a retried request or double-click
// never emails the customer twice. Email failures never roll back orders —
// they're logged and can be retried from the admin.
import { db } from './db.js'
import { escapeHtml as h } from './http.js'
import { formatCents as money } from './pricing.js'

const RESEND_API_KEY = Deno.env.get('RESEND_API_KEY')

/**
 * @param {object} p
 * @param {string} p.purpose
 * @param {string} p.to
 * @param {string} p.subject
 * @param {string} p.html
 * @param {string} [p.from]
 * @param {string} [p.replyTo]
 * @param {Array<{filename:string, content:string}>} [p.attachments]  base64 content
 * @param {string} [p.dedupeKey]
 * @param {boolean} [p.force]  resend even if already sent (admin "Resend")
 */
export async function sendEmail({ purpose, to, subject, html, from, replyTo, attachments, dedupeKey, force = false, orderId = null, projectId = null, invoiceId = null }) {
  let event = null
  if (dedupeKey) {
    const { data } = await db.from('shop_email_events').select('*').eq('dedupe_key', dedupeKey).maybeSingle()
    event = data
    if (event?.status === 'sent' && !force) return { status: 'sent', duplicate: true, event }
  }
  if (!event) {
    const { data, error } = await db.from('shop_email_events').insert({
      purpose, recipient: to, subject, order_id: orderId, project_id: projectId, invoice_id: invoiceId, dedupe_key: dedupeKey || null,
      payload: { html, from, replyTo, attachmentNames: (attachments || []).map(a => a.filename) },
    }).select().single()
    if (error) {
      // Lost a race with a concurrent identical send.
      if (error.code === '23505') return { status: 'sent', duplicate: true }
      console.error('email log failed', error)
    }
    event = data
  }

  if (!RESEND_API_KEY) {
    if (event) await db.from('shop_email_events').update({ status: 'skipped', error: 'RESEND_API_KEY not configured', attempts: (event.attempts || 0) + 1 }).eq('id', event.id)
    return { status: 'skipped', event }
  }

  try {
    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: { Authorization: `Bearer ${RESEND_API_KEY}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({ from, to: [to], subject, html, reply_to: replyTo || undefined, attachments: attachments?.length ? attachments : undefined }),
    })
    const body = await res.json().catch(() => ({}))
    if (!res.ok) throw new Error(body?.message || `Resend HTTP ${res.status}`)
    if (event) await db.from('shop_email_events').update({ status: 'sent', provider_id: body.id || null, error: null, sent_at: new Date().toISOString(), attempts: (event.attempts || 0) + 1 }).eq('id', event.id)
    return { status: 'sent', event }
  } catch (err) {
    console.error('email send failed', purpose, err)
    if (event) await db.from('shop_email_events').update({ status: 'failed', error: String(err.message || err), attempts: (event.attempts || 0) + 1 }).eq('id', event.id)
    return { status: 'failed', error: String(err.message || err), event }
  }
}

/** Re-sends a logged email (admin retry). Attachments are regenerated by the caller when needed. */
export async function retryEmail(eventId, { from }) {
  const { data: ev } = await db.from('shop_email_events').select('*').eq('id', eventId).single()
  if (!ev) return { status: 'failed', error: 'Not found' }
  return sendEmail({ purpose: ev.purpose, to: ev.recipient, subject: ev.subject, html: ev.payload?.html || '', from: ev.payload?.from || from, dedupeKey: ev.dedupe_key, force: true, orderId: ev.order_id, projectId: ev.project_id, invoiceId: ev.invoice_id })
}

// ── Templates ──────────────────────────────────────────────

export function layout(settings, title, bodyHtml) {
  const brand = h(settings.business_name || 'CGC Darts × MD Studios')
  return `<!doctype html><html><body style="margin:0;background:#f4f4f5;font-family:Inter,Segoe UI,Arial,sans-serif;color:#18181b">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f4f5;padding:24px 12px"><tr><td align="center">
<table width="100%" cellpadding="0" cellspacing="0" style="max-width:600px;background:#ffffff;border-radius:14px;overflow:hidden">
<tr><td style="background:#0b0b0c;padding:18px 24px;color:#fff;font-weight:900;font-size:18px;letter-spacing:-.01em">CGC<span style="color:#ff7a00">.</span> <span style="font-size:12px;font-weight:700;letter-spacing:.18em;text-transform:uppercase;color:#a1a1aa">${brand}</span></td></tr>
<tr><td style="height:4px;background:linear-gradient(90deg,#ff7a00,#ffb347);background-color:#ff7a00"></td></tr>
<tr><td style="padding:24px">
<h1 style="margin:0 0 12px;font-size:22px;font-weight:900">${h(title)}</h1>
${bodyHtml}
</td></tr>
<tr><td style="padding:16px 24px;background:#fafafa;color:#71717a;font-size:12px">${brand} · Prices in CAD${settings.contact_email ? ` · <a href="mailto:${h(settings.contact_email)}" style="color:#71717a">${h(settings.contact_email)}</a>` : ''}</td></tr>
</table></td></tr></table></body></html>`
}

const p = s => `<p style="margin:0 0 12px;line-height:1.55">${s}</p>`
const btn = (href, label) => `<p style="margin:18px 0"><a href="${h(href)}" style="display:inline-block;background:#ff7a00;color:#140800;font-weight:800;text-decoration:none;padding:12px 18px;border-radius:10px">${h(label)}</a></p>`

export function itemsTable(items) {
  const rows = items.map(it => {
    const opts = [it.colour, it.size, it.closure === 'zipper' ? 'Zipper' : 'Button', it.pocket ? 'Pocket' : 'No pocket', it.personalization ? `Name: ${it.personalization}` : null].filter(Boolean).join(' · ')
    return `<tr><td style="padding:8px 0;border-bottom:1px solid #eee"><b>${it.qty}×</b> ${h(it.product_name)}<div style="color:#71717a;font-size:12px">${h(opts)}</div></td><td align="right" style="padding:8px 0;border-bottom:1px solid #eee;white-space:nowrap">${money(it.line_cents)}</td></tr>`
  }).join('')
  return `<table width="100%" cellpadding="0" cellspacing="0" style="font-size:14px;margin:8px 0 12px">${rows}</table>`
}

export function totalsTable(t) {
  const row = (label, val, bold) => `<tr><td style="padding:3px 0;${bold ? 'font-weight:900;font-size:16px' : ''}">${label}</td><td align="right" style="padding:3px 0;${bold ? 'font-weight:900;font-size:16px' : ''}">${val}</td></tr>`
  return `<table width="100%" cellpadding="0" cellspacing="0" style="font-size:14px;border-top:1px solid #eee;padding-top:6px">
${row('Subtotal', money(t.subtotal_cents + (t.discount_cents || 0)))}
${t.discount_cents ? row('Discount', '−' + money(t.discount_cents)) : ''}
${row('Shipping', t.shipping_cents ? money(t.shipping_cents) : 'Free')}
${t.tax_cents ? row('Tax', money(t.tax_cents)) : ''}
${row('Total', money(t.total_cents), true)}
${t.credits_cents ? row('Paid / credited', '−' + money(t.credits_cents)) : ''}
${t.balance_cents != null && t.credits_cents ? row('Balance due', money(t.balance_cents), true) : ''}
</table>`
}

export function paymentBlock(settings, reference, amountCents) {
  return `<div style="margin:16px 0;padding:14px 16px;border:1px solid #fed7aa;background:#fff7ed;border-radius:10px;font-size:14px;line-height:1.6">
<b>Pay by Interac e-Transfer</b><br>
Amount: <b>${money(amountCents)} CAD</b><br>
Send to: <b>${h(settings.etransfer_email || '')}</b><br>
Message: <b>${h(reference)}</b><br>
<span style="color:#9a3412">${h(settings.etransfer_instructions || '')}</span></div>`
}

export const templates = {
  orderReceivedCustomer(settings, order, items, trackUrl) {
    return layout(settings, `Order received — ${order.order_number}`,
      p(`Hi ${h(order.contact_name.split(' ')[0])}, thanks for your order! Here’s what we received:`) +
      itemsTable(items) + totalsTable(order) +
      p('<b>What’s next:</b> we’ll review your order and email your invoice with Interac e-Transfer payment instructions. Your order is confirmed once payment is received and verified.') +
      btn(trackUrl || `${settings.shop_url}/track?order=${encodeURIComponent(order.order_number)}`, 'Track your order'))
  },
  orderReceivedAdmin(settings, order, items) {
    return layout(settings, `New ${order.order_type.toLowerCase()} order ${order.order_number}`,
      p(`<b>${h(order.contact_name)}</b> · ${h(order.contact_email)} · ${h(order.contact_phone || '')}`) +
      p(`${h([order.ship_street, order.ship_city, order.ship_province, order.ship_postal, order.ship_country].filter(Boolean).join(', '))}`) +
      (order.instructions ? p(`Notes: ${h(order.instructions)}`) : '') +
      itemsTable(items) + totalsTable(order) + btn(`${settings.shop_url}/admin/orders/${order.id}`, 'Open in admin'))
  },
  invoice(settings, inv, { reference, intro }) {
    return layout(settings, `Invoice ${inv.invoice_number}`,
      p(intro || 'Please find your invoice attached.') +
      totalsTable(inv) + paymentBlock(settings, reference, inv.balance_cents) +
      p('Questions? Just reply to this email.'))
  },
  receipt(settings, inv, { reference }) {
    return layout(settings, 'Payment received — order confirmed',
      p(`Thank you! We’ve received and verified your payment for <b>${h(reference)}</b>. Your order is confirmed and heading into production.`) +
      totalsTable({ ...inv, balance_cents: 0 }) + p('Your receipt is attached. We’ll email tracking details when your order ships.'))
  },
  paymentPartial(settings, { reference, paidCents, balanceCents }) {
    return layout(settings, 'Payment received',
      p(`We’ve received <b>${money(paidCents)}</b> toward <b>${h(reference)}</b>. Remaining balance: <b>${money(balanceCents)}</b>.`) +
      paymentBlock(settings, reference, balanceCents))
  },
  inquiryAck(settings, inq, customer) {
    return layout(settings, `Design request received — ${inq.inquiry_number}`,
      p(`Hi ${h(customer.name.split(' ')[0])}, thanks for your custom design request. We’ll review your brief and files and reply with a quote and next steps.`) +
      p(`Estimated shirts: <b>${inq.estimated_qty}</b> · Estimate: <b>${money(inq.estimate_cents)}</b> (including the $50 design fee). Final pricing uses your final quantity.`) +
      p('The one-time $50 design/setup/processing fee includes the initial shirt mockup and two rounds of requested design revisions. Additional revision rounds are available in packages of two for $25 each, charged only after you request and approve them.'))
  },
  inquiryAdmin(settings, inq, customer, project, fileCount) {
    return layout(settings, `New design inquiry ${inq.inquiry_number}`,
      p(`<b>${h(customer.name)}</b> · ${h(customer.email)} · ${h(customer.phone || '')}${inq.team ? ` · ${h(inq.team)}` : ''}`) +
      p(`Estimated qty: <b>${inq.estimated_qty}</b> · Estimate ${money(inq.estimate_cents)} · ${fileCount} file(s) attached`) +
      p(h(inq.brief).replace(/\n/g, '<br>')) + btn(`${settings.shop_url}/admin/projects/${project.id}`, 'Open project'))
  },
  privateLink(settings, project, customer, url) {
    return layout(settings, 'Your design is approved — place your order',
      p(`Hi ${h(customer.name.split(' ')[0])}, thanks for approving your design for <b>${h(project.title)}</b>. Use your private link below to choose sizes, styles and player names and submit your final order.`) +
      btn(url, 'Open my private order page') + p('<span style="color:#71717a;font-size:12px">This link is private to you — please don’t share it publicly.</span>'))
  },
  mockup(settings, project, customer, { roundLabel, note }) {
    return layout(settings, `${roundLabel} — ${project.title}`,
      p(`Hi ${h(customer.name.split(' ')[0])}, your ${h(roundLabel.toLowerCase())} for <b>${h(project.title)}</b> is attached.`) +
      (note ? p(h(note).replace(/\n/g, '<br>')) : '') +
      p('Reply to this email with any changes, or let us know you approve the design.'))
  },
  shipped(settings, order, s) {
    return layout(settings, `Your order ${order.order_number} has shipped`,
      p(`Good news — your order is on the way${s.carrier ? ` with <b>${h(s.carrier)}</b>` : ''}.`) +
      (s.tracking_number ? p(`Tracking number: <b>${h(s.tracking_number)}</b>`) : '') +
      (s.tracking_url ? btn(s.tracking_url, 'Track package') : btn(`${settings.shop_url}/track?order=${encodeURIComponent(order.order_number)}`, 'Track your order')))
  },
}
